### ISSUE TITLE
Automated tagging of releases

### ISSUE THREAD

**Issue by sciwhiz12** [ParchmentMC/Parchment#112]
It can be a pain to figure out from which commit a release was created for. Finding it out is certainly possible -- referencing the date of the release, knowing that releases are created at 12PM UTC on Sundays (as of writing), looking at past commits and finding the commit before that day) -- but it is still a time-consuming tag.

To alleviate this, we can implement the use of Git tags to mark releases, specifically using lightweight tags. During the release creation process, the CI should be able to create a lightweight tag on the latest commit in the release, and push it to the main repository.

While annotated tags would allow for attaching a message to the release, it would be more difficult to configure because of the requirement of a committer identity to the CI agent just before creating the annotated tag. However, we may reconsider on this point if it proves that the benefits of using annotated tags outweights the difficulty in CI configuration.

**Comment by marchermans** [comment]
Implemented in TeamCity.
Will happen for Nightly and Releases but not for bleeding.

**Comment by sciwhiz12** [comment]
For reference, the built commit for the following artifact type is tagged with the given format:
- Releases: `releases/<MC version>-<Parchment version>`
- Nightly: `nightly/<MC version>-<Parchment version>`
- Bleeding artifacts are kept untagged.

**N.B.:** Because of how the build configurations are currently configured, release commits are tagged for both `releases/` and `nightly/`.
