### ISSUE TITLE
First-time user feedback

### ISSUE THREAD

**Issue by mezz** [ParchmentMC/Parchment#113]
Hello!

I recently went through learning about parchment and setting it up on my project and I have some feedback about minor roadblocks I hit.

The first place I landed was https://parchmentmc.org/ but I found it difficult to understand what Parchment was, and there was no way for me see how to set it up in my project. It actually took some digging through GitHub and other places before I found out how to set it up, and I never found information about what exactly it accomplishes or what its limitations are.

It seems like the current information is optimized for contributors, but I think at this stage it should shift to focus primarily on users.

I think the most streamlined experience would be a simple-to-understand "before and after" screenshot of your IDE where you have messed up parameter names, and then tada parchment is added and you can understand.
Then, jump right into the wiki on setting up your `build.gradle`.
I think that's all a user needs to get on board, everything else is icing on top and people can get funneled there as they dig deeper.

Thanks for the mappings!

**Comment by sciwhiz12** [comment]
Thank you for the feedback! We'll look into enhancing the user-side introduction and experience to Parchment, especially at the website. 

I've been meaning to look into improving the website experience, but my lack of time and experience with Jekyll sites in general have made that a tad difficult at the moment. (Particularly, I've wanted to modify the theme/skin of the site, but choosing a theme that 'fits' is harder than it seems for me. 😅)

At the very least, I do want to enhance the main page of the website, and probably add a FAQ page or move (partially or fully) the [existing FAQ page on this repo's wiki](https://github.com/ParchmentMC/Parchment/wiki/Frequently-Asked-Questions) over to the site. There is also a filed issue on the website repo for some previous feedback on the website: ParchmentMC/Website#6.

**Comment by cpw** [comment]
Going to echo this. This looks like an awful rabbit hole with unknown depths to even get started. It is not clear what I'm supposed to do or how, or why.

**Comment by Toma400** [comment]
I agree. At the time of 1.16 (and especially with coverage of KaupenJoe) it was pretty clear how to work with mappings, but nowadays I find it fairly difficult to implement mappings, on 1.19 specifically.
