### ISSUE TITLE
1.19 Port

### ISSUE THREAD

**Issue by BurnutsGaming** [ParchmentMC/Parchment#121]
You might need to port to 1.19 because there is already Forge 1.19 which just took a few hours for them to port to 1.19 along with Fabric so they can still use it in 1.19.

**Comment by BurnutsGaming** [comment]
Nevermind

**Comment by sciwhiz12** [comment]
For others who may find this issue;

For Forge developers, Librarian has the [cross version mappings](https://github.com/ParchmentMC/Librarian/blob/dev/docs/FORGEGRADLE.md#cross-version-mappings) feature which allows using Parchment mappings built for a specific Minecraft version on another Minecraft version.
For Fabric/Quilt developers, Fabric/Quilt Loom's support for Parchment mappings is through its layered mappings system, which handles using mappings built for a specific Minecraft version on another Minecraft version.

We will be working on updating to 1.19 within the coming week(s). For now, developers can use 1.18.2 mappings using the above features, or fallback to Mojmaps until a 1.19 release is published (as Parchment is inherently compatible/interchangable with Mojmaps).

**Comment by BurnutsGaming** [comment]
> For others who may find this issue;
> 
> For Forge developers, Librarian has the [cross version mappings](https://github.com/ParchmentMC/Librarian/blob/dev/docs/FORGEGRADLE.md#cross-version-mappings) feature which allows using Parchment mappings built for a specific Minecraft version on another Minecraft version. For Fabric/Quilt developers, Fabric/Quilt Loom's support for Parchment mappings is through its layered mappings system, which handles using mappings built for a specific Minecraft version on another Minecraft version.
> 
> We will be working on updating to 1.19 within the coming week(s). For now, developers can use 1.18.2 mappings using the above features, or fallback to Mojmaps until a 1.19 release is published (as Parchment is inherently compatible/interchangable with Mojmaps).

Thanks @sciwhiz12.

**Comment by SzczurekYT** [comment]
Maybe this should stay open so pepole like me won't post duplicates?

**Comment by MelanX** [comment]
I think pinning the issue on top would be a better solution.
