### ISSUE TITLE
Release for 1.19?

### ISSUE THREAD

**Issue by SzczurekYT** [ParchmentMC/Parchment#122]
Hello.
Could you please add a release for 1.19?
Thnaks

**Comment by AterAnimAvis** [comment]
See Sci's comment here <https://github.com/ParchmentMC/Parchment/issues/121#issuecomment-1149729109>

Especially:
>We will be working on updating to 1.19 within the coming week(s). For now, developers can use 1.18.2 mappings using the above features, or fallback to Mojmaps until a 1.19 release is published (as Parchment is inherently compatible/interchangable with Mojmaps).
