### ISSUE TITLE
org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'org.parchmentmc.librarian.forgegradle', version: '1.+'] was not found in any of the following sources

### ISSUE THREAD

**Issue by RealYusufIsmail** [ParchmentMC/Parchment#157]
Just happened now, was working before

**Comment by Lanse505** [comment]
We're migrating services, this was posted on our discord earlier today.

**Comment by RealYusufIsmail** [comment]
whats the discord server link @Lanse505

**Comment by Lanse505** [comment]
There's a widget on this repos main page >.>
![bild](https://user-images.githubusercontent.com/1495068/182445809-27dda06f-c7df-4a15-95d1-ce285a207881.png)

**Comment by RealYusufIsmail** [comment]
the site is down

**Comment by Lanse505** [comment]
https://discord.gg/6yTSRqcTUE <--- Use that temporarily

**Comment by RealYusufIsmail** [comment]
thx
