### ISSUE TITLE
Needs mappings update for 22w43a or beyond

### ISSUE THREAD

**Issue by ghost** [ParchmentMC/Parchment#184]
Needs mappings update for 22w43a or beyond. I porting Polymorph mod for latest snapshot of Minecraft. Some mappings are incorrect or still obfuscated.

**Comment by zml2008** [comment]
Parchment typically doesn't target snapshots.

**Comment by marchermans** [comment]
This is normal we don't target snapshots as we value quality above quantity

**Comment by marchermans** [comment]
This is normal we don't target snapshots as we value quality above quantity
