### ISSUE TITLE
p_44001_ and p_267165_ missing

### ISSUE THREAD

**Issue by wolfieboy09** [ParchmentMC/Parchment#285]
**Minecraft version:**  `1.20.1`
**Mappings version:** `2023.09.03-1.20.1`

`p_44001_` should be `simpleContainer` and `p_267165_` should be `registryAccess`

**Before**
![image](https://github.com/ParchmentMC/Parchment/assets/105564186/9089c3fa-79a5-44d2-82ab-79ace3d07ad0)
 **What it should be**
 
![image](https://github.com/ParchmentMC/Parchment/assets/105564186/77d6f63b-a50e-4dfb-a019-37defa3ccfb4)

Or simpleContainer could just be container

**Comment by sciwhiz12** [comment]
Could you please provide more information on which class this is?

**Comment by Lanse505** [comment]
Since this has been an inactive issue for over 4 months, and author has not provided the requested information. I'm closing this.
