### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by Xplodin** [ParchmentMC/Parchment#286]
*[If your topic fits an already existing template, please use those for the proper labels to be applied.]*
![image](https://github.com/ParchmentMC/Parchment/assets/13007677/bfb94fbf-c0ab-4709-8012-885b20d21eac)

**Comment by Lanse505** [comment]
We know, this is being worked on, please be patient.

**Comment by GatoDev** [comment]
For people who have the problem, for the time being to fix it use this: https://web.archive.org/web/20240410224528/https://parchmentmc.org/docs/getting-started

**Comment by sciwhiz12** [comment]
The website has been fixed.
