### ISSUE TITLE
p_333627_ mapping missing

### ISSUE THREAD

**Issue by xXmadajaXx** [ParchmentMC/Parchment#287]
**Minecraft version:** *1.20.6*
**Mappings version:** *2024.06.16*

*A lot of mappings are missing in the Gui.java class such as p_333627_ aswell as many more*

**Comment by Lanse505** [comment]
Feel free to make a PR for this, I think as of currently this should be mapped in the upcoming 1.12.3 mappings (#307) submitted by @PiTheGuy anyway.

If you need this for specifically 1.20.6, my recommendation is submitting a PR for it :)
