### ISSUE TITLE
When using curseforge repositories and using curseforge mods as dependencies, an error occurs

### ISSUE THREAD

**Issue by DimLoong** [ParchmentMC/Parchment#295]
The following is the build.gradle file, which has been used for parchment

`repositories {maven {url = "https://www.cursemaven.com" }}`

`dependencies {implementation fg.deobf('curse.maven:framework-549225:4613856')}`

Error message

`> Could not find curse.maven:framework-549225:4613856_mapped_parchment_2022.08.07-1.18.2.`
`Searched in the following locations:`
`- file:/C:/Users/-/.gradle/caches/forge_gradle/bundled_deobf_repo/curse/maven/framework-549225/4613856_mapped_parchment_2022.08.07-1.18.2/framework-549225-4613856_mapped_parchment_2022.08.07-1.18.2.pom`
`- file:/C:/Users/-/.gradle/caches/forge_gradle/bundled_deobf_repo/curse/maven/framework-549225/4613856_mapped_parchment_2022.08.07-1.18.2/framework-549225-4613856_mapped_parchment_2022.08.07-1.18.2.jar`
`Required by:`
`project :`

**Comment by AterAnimAvis** [comment]
That dependency and parchment version work for me.
I'd suggest looking further up in the logs, that error has a habbit of masking an earlier error due to it's nature of being a generated artifact.
Most likely case here is that you've added the CurseMaven repository to the wrong repositories block.

**Comment by Lanse505** [comment]
Is this problem still valid? @DimLoong

**Comment by Matyrobbrt** [comment]
Closing this as the OP hasn't replied. As @AterAnimAvis pointed out, these errors are usually not due to Parchment and they hide the actual error which can be found higher up in the log.
