### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by the-one-with-raspberry** [ParchmentMC/Parchment#306]
When going to [https://parchmentmc.org](https://parchmentmc.org) and giving the website some time to load, it returns a "Request Timed Out" message from Cloudflare. When using cURL, it times out too.

**Comment by sciwhiz12** [comment]
The issue should be fixed. One of the ingress nodes that serves the website is/was not responding correctly, and has been taken out of service for serving parchmentmc.org and parchmentmc.net.

If you are unable to connect, please send a message in the Discord server or leave a comment in this issue. Thanks!

**Comment by the-one-with-raspberry** [comment]
Solved. Thanks!
