### ISSUE TITLE
parchment conflict with curseforge dependency

### ISSUE THREAD

**Issue by yzqdev** [ParchmentMC/Parchment#311]
I have made a minimal repo for reproduction.https://github.com/yzqdev/forge-1.20.1-47.3.0-mdk

gradle sync is ok, while when we run forge  `runClient` command, it throws such an error

```
Execution failed for task ':runClient'.
> Could not resolve all files for configuration ':runtimeClasspathCopy'.
   > Could not find curse.maven:catalogue-459701:4766090_mapped_parchment_2023.09.03-1.20.1.
     Required by:
         root project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

## significant code blocks
parchment version
```
 minecraft {
     mappings channel: 'parchment', version: '2023.09.03-1.20.1'
 }
```

`build.gradle `
```
repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        filter {
            includeGroup "curse.maven"
        }
    }
}
```

more details, see my reproduction repo https://github.com/yzqdev/forge-1.20.1-47.3.0-mdk  run  forge`runClient`.

**Comment by AterAnimAvis** [comment]
This is a Buildscript/ForgeGradle issue, not a Parchment one.
ForgeGradle uses a custom repository (along with transforming the artifact name) for providing deobfuscated artifacts (via `fg.deobf`) your `exclusiveContent` block is preventing that repo from providing the transformed artifact.

To make this work you need to also include the `fg.repository` in your `exclusiveContent` block

```
repositories {
    exclusiveContent {
        forRepository {
            maven {
                url "https://cursemaven.com"
            }
        }
        forRepositories(fg.repository) // Allow ForgeGradle to provide deobfuscated artifacts
        filter {
            includeGroup "curse.maven"
        }
    }
}
```

(See also the Issue on ForgeGradle's repo <https://github.com/MinecraftForge/ForgeGradle/issues/925>)
