### ISSUE TITLE
add supported versions json to maven.

### ISSUE THREAD

**Issue by wagyourtail** [ParchmentMC/Parchment#63]
It is difficult to programatically determine available minecraft versions for parchment. it would be great if there was a file somewhere on the maven containing supported minecraft versions.
I'm thinking somewhere like `org/parchmentmc/data/parchment-versions.json`
and the contents would be something like
```json
[
 "1.16.5", "1.17", "1.17.1"
]
```

**Comment by Toma400** [comment]
It'd be cool to add all versions listed, maybe under .md extension, since it's more user-friendly

**Comment by marchermans** [comment]
This is already discussed, read the `maven-metadata.xml`, which exists exactly for this reason.
